version: 1.0.{build}
environment:
  matrix:
    # array of all environments used to test builds
    - GENERATOR: Visual Studio 14 2015
      CFG: Debug
      VS_VERSION: 14.0
#    - GENERATOR: Visual Studio 12 2013
#      CFG: Debug
#      VS_VERSION: 12.0
#    - GENERATOR: Visual Studio 14 2015 Win64
#      CFG: Debug
#      VS_VERSION: 14.0
    - GENERATOR: Visual Studio 12 2013 Win64
      CFG: Debug
      VS_VERSION: 12.0
    - GENERATOR: Visual Studio 14 2015 ARM
      CFG: Debug
      VS_VERSION: 14.0

cache:
  - "%LocalAppData%\\pip"
#  - "C:\\Python27\\Lib\\site-packages"

# Workaround for http://help.appveyor.com/discussions/problems/4569
before_build:
  - del "C:\Program Files (x86)\MSBuild\%VS_VERSION%\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build:
  parallel: true

build_script:
    # enable calling pip directly
  - cmd: set PATH=%SystemDrive%\Python27\Scripts;%PATH%
  - cmd: pip install autobahntestsuite
  - cmd: wstest --autobahnversion
  - cmd: cmake --version
  - cmd: git submodule update --init
  - cmd: IF NOT %VS_VERSION% == NONE call "C:/Program Files (x86)/Microsoft Visual Studio %VS_VERSION%/Common7/Tools/vsvars32.bat"
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" -DFTW_LVIDE_PATH="../.ci" ../kernel
  - cmd: cmake --build .

test_script:
  - cmd: ctest --output-on-failure --build-config "%CFG%" .
